version: "3.9"
services:
  web:
    build: "."
    image: "notes:latest"
    ports:
      - "8080:8080"
    volumes:
      - "./:/var/www/html"
    command: 'sh -c "composer install && supervisord -c /etc/supervisor/conf.d/supervisord.conf"'

  db:
    image: "mariadb"
    restart: "always"
    environment:
      MARIADB_DATABASE: "tm-notes"
      MARIADB_USER: "root"
      MARIADB_ROOT_PASSWORD: "Pas_W0rd"
    ports:
      - "3306:3306"
    volumes:
      - "./var/lib/mysql:/var/lib/mysql"
      - "./docker/mysql/sql:/docker-entrypoint-initdb.d" # load sql files from here on a fresh start

  node:
    image: "node"
    user: "node"
    working_dir: /home/node/app
    ports:
      - "3000:3000"
    volumes:
      - "./notes-frontend:/home/node/app"
    command: 'sh -c "npm install && npm start"'
